package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class AlarmRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarm_content
     *
     * @mbg.generated
     */
    private String alarmContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.read_flag
     *
     * @mbg.generated
     */
    private Integer readFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.id
     *
     * @return the value of alarm_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.id
     *
     * @param id the value for alarm_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.user_id
     *
     * @return the value of alarm_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.user_id
     *
     * @param userId the value for alarm_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarm_content
     *
     * @return the value of alarm_record.alarm_content
     *
     * @mbg.generated
     */
    public String getAlarmContent() {
        return alarmContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarm_content
     *
     * @param alarmContent the value for alarm_record.alarm_content
     *
     * @mbg.generated
     */
    public void setAlarmContent(String alarmContent) {
        this.alarmContent = alarmContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.read_flag
     *
     * @return the value of alarm_record.read_flag
     *
     * @mbg.generated
     */
    public Integer getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.read_flag
     *
     * @param readFlag the value for alarm_record.read_flag
     *
     * @mbg.generated
     */
    public void setReadFlag(Integer readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.create_time
     *
     * @return the value of alarm_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.create_time
     *
     * @param createTime the value for alarm_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.update_time
     *
     * @return the value of alarm_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.update_time
     *
     * @param updateTime the value for alarm_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}