package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class AlarmSet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.time_threshold
     *
     * @mbg.generated
     */
    private Integer timeThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.qps_threshold
     *
     * @mbg.generated
     */
    private Integer qpsThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.monitor_item_id
     *
     * @mbg.generated
     */
    private Integer monitorItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_set.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.id
     *
     * @return the value of alarm_set.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.id
     *
     * @param id the value for alarm_set.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.time_threshold
     *
     * @return the value of alarm_set.time_threshold
     *
     * @mbg.generated
     */
    public Integer getTimeThreshold() {
        return timeThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.time_threshold
     *
     * @param timeThreshold the value for alarm_set.time_threshold
     *
     * @mbg.generated
     */
    public void setTimeThreshold(Integer timeThreshold) {
        this.timeThreshold = timeThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.qps_threshold
     *
     * @return the value of alarm_set.qps_threshold
     *
     * @mbg.generated
     */
    public Integer getQpsThreshold() {
        return qpsThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.qps_threshold
     *
     * @param qpsThreshold the value for alarm_set.qps_threshold
     *
     * @mbg.generated
     */
    public void setQpsThreshold(Integer qpsThreshold) {
        this.qpsThreshold = qpsThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.monitor_item_id
     *
     * @return the value of alarm_set.monitor_item_id
     *
     * @mbg.generated
     */
    public Integer getMonitorItemId() {
        return monitorItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.monitor_item_id
     *
     * @param monitorItemId the value for alarm_set.monitor_item_id
     *
     * @mbg.generated
     */
    public void setMonitorItemId(Integer monitorItemId) {
        this.monitorItemId = monitorItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.group_id
     *
     * @return the value of alarm_set.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.group_id
     *
     * @param groupId the value for alarm_set.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.user_id
     *
     * @return the value of alarm_set.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.user_id
     *
     * @param userId the value for alarm_set.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.delete_flag
     *
     * @return the value of alarm_set.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.delete_flag
     *
     * @param deleteFlag the value for alarm_set.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.create_time
     *
     * @return the value of alarm_set.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.create_time
     *
     * @param createTime the value for alarm_set.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_set.update_time
     *
     * @return the value of alarm_set.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_set.update_time
     *
     * @param updateTime the value for alarm_set.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}