package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class MonitorDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.request_type
     *
     * @mbg.generated
     */
    private String requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.request_count
     *
     * @mbg.generated
     */
    private Integer requestCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.request_time
     *
     * @mbg.generated
     */
    private Long requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.avg_time
     *
     * @mbg.generated
     */
    private Long avgTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.monitor_item_id
     *
     * @mbg.generated
     */
    private Integer monitorItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_detail.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.id
     *
     * @return the value of monitor_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.id
     *
     * @param id the value for monitor_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.ip
     *
     * @return the value of monitor_detail.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.ip
     *
     * @param ip the value for monitor_detail.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.request_type
     *
     * @return the value of monitor_detail.request_type
     *
     * @mbg.generated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.request_type
     *
     * @param requestType the value for monitor_detail.request_type
     *
     * @mbg.generated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.request_count
     *
     * @return the value of monitor_detail.request_count
     *
     * @mbg.generated
     */
    public Integer getRequestCount() {
        return requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.request_count
     *
     * @param requestCount the value for monitor_detail.request_count
     *
     * @mbg.generated
     */
    public void setRequestCount(Integer requestCount) {
        this.requestCount = requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.request_time
     *
     * @return the value of monitor_detail.request_time
     *
     * @mbg.generated
     */
    public Long getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.request_time
     *
     * @param requestTime the value for monitor_detail.request_time
     *
     * @mbg.generated
     */
    public void setRequestTime(Long requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.avg_time
     *
     * @return the value of monitor_detail.avg_time
     *
     * @mbg.generated
     */
    public Long getAvgTime() {
        return avgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.avg_time
     *
     * @param avgTime the value for monitor_detail.avg_time
     *
     * @mbg.generated
     */
    public void setAvgTime(Long avgTime) {
        this.avgTime = avgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.monitor_item_id
     *
     * @return the value of monitor_detail.monitor_item_id
     *
     * @mbg.generated
     */
    public Integer getMonitorItemId() {
        return monitorItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.monitor_item_id
     *
     * @param monitorItemId the value for monitor_detail.monitor_item_id
     *
     * @mbg.generated
     */
    public void setMonitorItemId(Integer monitorItemId) {
        this.monitorItemId = monitorItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.create_time
     *
     * @return the value of monitor_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.create_time
     *
     * @param createTime the value for monitor_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_detail.update_time
     *
     * @return the value of monitor_detail.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_detail.update_time
     *
     * @param updateTime the value for monitor_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}