package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class MonitorProjectUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_user.monitor_token
     *
     * @mbg.generated
     */
    private Integer monitorToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_user.id
     *
     * @return the value of monitor_project_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_user.id
     *
     * @param id the value for monitor_project_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_user.monitor_token
     *
     * @return the value of monitor_project_user.monitor_token
     *
     * @mbg.generated
     */
    public Integer getMonitorToken() {
        return monitorToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_user.monitor_token
     *
     * @param monitorToken the value for monitor_project_user.monitor_token
     *
     * @mbg.generated
     */
    public void setMonitorToken(Integer monitorToken) {
        this.monitorToken = monitorToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_user.user_id
     *
     * @return the value of monitor_project_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_user.user_id
     *
     * @param userId the value for monitor_project_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_user.create_time
     *
     * @return the value of monitor_project_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_user.create_time
     *
     * @param createTime the value for monitor_project_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_user.update_time
     *
     * @return the value of monitor_project_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_user.update_time
     *
     * @param updateTime the value for monitor_project_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}