package com.ych.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MonitorSummaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public MonitorSummaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMonitorNameIsNull() {
            addCriterion("monitor_name is null");
            return (Criteria) this;
        }

        public Criteria andMonitorNameIsNotNull() {
            addCriterion("monitor_name is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorNameEqualTo(String value) {
            addCriterion("monitor_name =", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameNotEqualTo(String value) {
            addCriterion("monitor_name <>", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameGreaterThan(String value) {
            addCriterion("monitor_name >", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_name >=", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameLessThan(String value) {
            addCriterion("monitor_name <", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameLessThanOrEqualTo(String value) {
            addCriterion("monitor_name <=", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameLike(String value) {
            addCriterion("monitor_name like", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameNotLike(String value) {
            addCriterion("monitor_name not like", value, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameIn(List<String> values) {
            addCriterion("monitor_name in", values, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameNotIn(List<String> values) {
            addCriterion("monitor_name not in", values, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameBetween(String value1, String value2) {
            addCriterion("monitor_name between", value1, value2, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMonitorNameNotBetween(String value1, String value2) {
            addCriterion("monitor_name not between", value1, value2, "monitorName");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeIsNull() {
            addCriterion("max_request_time is null");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeIsNotNull() {
            addCriterion("max_request_time is not null");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeEqualTo(Long value) {
            addCriterion("max_request_time =", value, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeNotEqualTo(Long value) {
            addCriterion("max_request_time <>", value, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeGreaterThan(Long value) {
            addCriterion("max_request_time >", value, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("max_request_time >=", value, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeLessThan(Long value) {
            addCriterion("max_request_time <", value, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeLessThanOrEqualTo(Long value) {
            addCriterion("max_request_time <=", value, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeIn(List<Long> values) {
            addCriterion("max_request_time in", values, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeNotIn(List<Long> values) {
            addCriterion("max_request_time not in", values, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeBetween(Long value1, Long value2) {
            addCriterion("max_request_time between", value1, value2, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andMaxRequestTimeNotBetween(Long value1, Long value2) {
            addCriterion("max_request_time not between", value1, value2, "maxRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeIsNull() {
            addCriterion("total_request_time is null");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeIsNotNull() {
            addCriterion("total_request_time is not null");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeEqualTo(Long value) {
            addCriterion("total_request_time =", value, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeNotEqualTo(Long value) {
            addCriterion("total_request_time <>", value, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeGreaterThan(Long value) {
            addCriterion("total_request_time >", value, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("total_request_time >=", value, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeLessThan(Long value) {
            addCriterion("total_request_time <", value, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeLessThanOrEqualTo(Long value) {
            addCriterion("total_request_time <=", value, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeIn(List<Long> values) {
            addCriterion("total_request_time in", values, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeNotIn(List<Long> values) {
            addCriterion("total_request_time not in", values, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeBetween(Long value1, Long value2) {
            addCriterion("total_request_time between", value1, value2, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andTotalRequestTimeNotBetween(Long value1, Long value2) {
            addCriterion("total_request_time not between", value1, value2, "totalRequestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNull() {
            addCriterion("request_type is null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNotNull() {
            addCriterion("request_type is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeEqualTo(String value) {
            addCriterion("request_type =", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotEqualTo(String value) {
            addCriterion("request_type <>", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThan(String value) {
            addCriterion("request_type >", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThanOrEqualTo(String value) {
            addCriterion("request_type >=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThan(String value) {
            addCriterion("request_type <", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThanOrEqualTo(String value) {
            addCriterion("request_type <=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLike(String value) {
            addCriterion("request_type like", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotLike(String value) {
            addCriterion("request_type not like", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIn(List<String> values) {
            addCriterion("request_type in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotIn(List<String> values) {
            addCriterion("request_type not in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeBetween(String value1, String value2) {
            addCriterion("request_type between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotBetween(String value1, String value2) {
            addCriterion("request_type not between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andMonitorHostIsNull() {
            addCriterion("monitor_host is null");
            return (Criteria) this;
        }

        public Criteria andMonitorHostIsNotNull() {
            addCriterion("monitor_host is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorHostEqualTo(String value) {
            addCriterion("monitor_host =", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostNotEqualTo(String value) {
            addCriterion("monitor_host <>", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostGreaterThan(String value) {
            addCriterion("monitor_host >", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_host >=", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostLessThan(String value) {
            addCriterion("monitor_host <", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostLessThanOrEqualTo(String value) {
            addCriterion("monitor_host <=", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostLike(String value) {
            addCriterion("monitor_host like", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostNotLike(String value) {
            addCriterion("monitor_host not like", value, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostIn(List<String> values) {
            addCriterion("monitor_host in", values, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostNotIn(List<String> values) {
            addCriterion("monitor_host not in", values, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostBetween(String value1, String value2) {
            addCriterion("monitor_host between", value1, value2, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andMonitorHostNotBetween(String value1, String value2) {
            addCriterion("monitor_host not between", value1, value2, "monitorHost");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andRequestCountIsNull() {
            addCriterion("request_count is null");
            return (Criteria) this;
        }

        public Criteria andRequestCountIsNotNull() {
            addCriterion("request_count is not null");
            return (Criteria) this;
        }

        public Criteria andRequestCountEqualTo(Integer value) {
            addCriterion("request_count =", value, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountNotEqualTo(Integer value) {
            addCriterion("request_count <>", value, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountGreaterThan(Integer value) {
            addCriterion("request_count >", value, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("request_count >=", value, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountLessThan(Integer value) {
            addCriterion("request_count <", value, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountLessThanOrEqualTo(Integer value) {
            addCriterion("request_count <=", value, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountIn(List<Integer> values) {
            addCriterion("request_count in", values, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountNotIn(List<Integer> values) {
            addCriterion("request_count not in", values, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountBetween(Integer value1, Integer value2) {
            addCriterion("request_count between", value1, value2, "requestCount");
            return (Criteria) this;
        }

        public Criteria andRequestCountNotBetween(Integer value1, Integer value2) {
            addCriterion("request_count not between", value1, value2, "requestCount");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andHandleFlagIsNull() {
            addCriterion("handle_flag is null");
            return (Criteria) this;
        }

        public Criteria andHandleFlagIsNotNull() {
            addCriterion("handle_flag is not null");
            return (Criteria) this;
        }

        public Criteria andHandleFlagEqualTo(Integer value) {
            addCriterion("handle_flag =", value, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagNotEqualTo(Integer value) {
            addCriterion("handle_flag <>", value, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagGreaterThan(Integer value) {
            addCriterion("handle_flag >", value, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("handle_flag >=", value, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagLessThan(Integer value) {
            addCriterion("handle_flag <", value, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagLessThanOrEqualTo(Integer value) {
            addCriterion("handle_flag <=", value, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagIn(List<Integer> values) {
            addCriterion("handle_flag in", values, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagNotIn(List<Integer> values) {
            addCriterion("handle_flag not in", values, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagBetween(Integer value1, Integer value2) {
            addCriterion("handle_flag between", value1, value2, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andHandleFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("handle_flag not between", value1, value2, "handleFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monitor_summary
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}