package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class MonitorGroupItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_group_item.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_group_item.monitor_item_id
     *
     * @mbg.generated
     */
    private Integer monitorItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_group_item.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_group_item.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_group_item.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_group_item.id
     *
     * @return the value of monitor_group_item.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_group_item.id
     *
     * @param id the value for monitor_group_item.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_group_item.monitor_item_id
     *
     * @return the value of monitor_group_item.monitor_item_id
     *
     * @mbg.generated
     */
    public Integer getMonitorItemId() {
        return monitorItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_group_item.monitor_item_id
     *
     * @param monitorItemId the value for monitor_group_item.monitor_item_id
     *
     * @mbg.generated
     */
    public void setMonitorItemId(Integer monitorItemId) {
        this.monitorItemId = monitorItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_group_item.group_id
     *
     * @return the value of monitor_group_item.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_group_item.group_id
     *
     * @param groupId the value for monitor_group_item.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_group_item.create_time
     *
     * @return the value of monitor_group_item.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_group_item.create_time
     *
     * @param createTime the value for monitor_group_item.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_group_item.update_time
     *
     * @return the value of monitor_group_item.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_group_item.update_time
     *
     * @param updateTime the value for monitor_group_item.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}