package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class MonitorItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_item.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_item.monitor_item_name
     *
     * @mbg.generated
     */
    private String monitorItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_item.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_item.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_item.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_item.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_item.id
     *
     * @return the value of monitor_item.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_item.id
     *
     * @param id the value for monitor_item.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_item.monitor_item_name
     *
     * @return the value of monitor_item.monitor_item_name
     *
     * @mbg.generated
     */
    public String getMonitorItemName() {
        return monitorItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_item.monitor_item_name
     *
     * @param monitorItemName the value for monitor_item.monitor_item_name
     *
     * @mbg.generated
     */
    public void setMonitorItemName(String monitorItemName) {
        this.monitorItemName = monitorItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_item.project_name
     *
     * @return the value of monitor_item.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_item.project_name
     *
     * @param projectName the value for monitor_item.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_item.project_id
     *
     * @return the value of monitor_item.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_item.project_id
     *
     * @param projectId the value for monitor_item.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_item.create_time
     *
     * @return the value of monitor_item.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_item.create_time
     *
     * @param createTime the value for monitor_item.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_item.update_time
     *
     * @return the value of monitor_item.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_item.update_time
     *
     * @param updateTime the value for monitor_item.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}