package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class MonitorSummary implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.monitor_name
     *
     * @mbg.generated
     */
    private String monitorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.max_request_time
     *
     * @mbg.generated
     */
    private Long maxRequestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.total_request_time
     *
     * @mbg.generated
     */
    private Long totalRequestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.request_type
     *
     * @mbg.generated
     */
    private String requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.monitor_host
     *
     * @mbg.generated
     */
    private String monitorHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.request_count
     *
     * @mbg.generated
     */
    private Integer requestCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.handle_flag
     *
     * @mbg.generated
     */
    private Integer handleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_summary.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.id
     *
     * @return the value of monitor_summary.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.id
     *
     * @param id the value for monitor_summary.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.monitor_name
     *
     * @return the value of monitor_summary.monitor_name
     *
     * @mbg.generated
     */
    public String getMonitorName() {
        return monitorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.monitor_name
     *
     * @param monitorName the value for monitor_summary.monitor_name
     *
     * @mbg.generated
     */
    public void setMonitorName(String monitorName) {
        this.monitorName = monitorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.max_request_time
     *
     * @return the value of monitor_summary.max_request_time
     *
     * @mbg.generated
     */
    public Long getMaxRequestTime() {
        return maxRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.max_request_time
     *
     * @param maxRequestTime the value for monitor_summary.max_request_time
     *
     * @mbg.generated
     */
    public void setMaxRequestTime(Long maxRequestTime) {
        this.maxRequestTime = maxRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.total_request_time
     *
     * @return the value of monitor_summary.total_request_time
     *
     * @mbg.generated
     */
    public Long getTotalRequestTime() {
        return totalRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.total_request_time
     *
     * @param totalRequestTime the value for monitor_summary.total_request_time
     *
     * @mbg.generated
     */
    public void setTotalRequestTime(Long totalRequestTime) {
        this.totalRequestTime = totalRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.request_type
     *
     * @return the value of monitor_summary.request_type
     *
     * @mbg.generated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.request_type
     *
     * @param requestType the value for monitor_summary.request_type
     *
     * @mbg.generated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.monitor_host
     *
     * @return the value of monitor_summary.monitor_host
     *
     * @mbg.generated
     */
    public String getMonitorHost() {
        return monitorHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.monitor_host
     *
     * @param monitorHost the value for monitor_summary.monitor_host
     *
     * @mbg.generated
     */
    public void setMonitorHost(String monitorHost) {
        this.monitorHost = monitorHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.create_date
     *
     * @return the value of monitor_summary.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.create_date
     *
     * @param createDate the value for monitor_summary.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.request_count
     *
     * @return the value of monitor_summary.request_count
     *
     * @mbg.generated
     */
    public Integer getRequestCount() {
        return requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.request_count
     *
     * @param requestCount the value for monitor_summary.request_count
     *
     * @mbg.generated
     */
    public void setRequestCount(Integer requestCount) {
        this.requestCount = requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.project_id
     *
     * @return the value of monitor_summary.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.project_id
     *
     * @param projectId the value for monitor_summary.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.handle_flag
     *
     * @return the value of monitor_summary.handle_flag
     *
     * @mbg.generated
     */
    public Integer getHandleFlag() {
        return handleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.handle_flag
     *
     * @param handleFlag the value for monitor_summary.handle_flag
     *
     * @mbg.generated
     */
    public void setHandleFlag(Integer handleFlag) {
        this.handleFlag = handleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.create_time
     *
     * @return the value of monitor_summary.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.create_time
     *
     * @param createTime the value for monitor_summary.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_summary.update_time
     *
     * @return the value of monitor_summary.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_summary.update_time
     *
     * @param updateTime the value for monitor_summary.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}