package com.ych.core.model;

import java.io.Serializable;
import java.util.Date;

public class MonitorProjectUrl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_url.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_url.monitor_url
     *
     * @mbg.generated
     */
    private String monitorUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_url.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_url.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_project_url.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_project_url
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_url.id
     *
     * @return the value of monitor_project_url.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_url.id
     *
     * @param id the value for monitor_project_url.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_url.monitor_url
     *
     * @return the value of monitor_project_url.monitor_url
     *
     * @mbg.generated
     */
    public String getMonitorUrl() {
        return monitorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_url.monitor_url
     *
     * @param monitorUrl the value for monitor_project_url.monitor_url
     *
     * @mbg.generated
     */
    public void setMonitorUrl(String monitorUrl) {
        this.monitorUrl = monitorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_url.project_id
     *
     * @return the value of monitor_project_url.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_url.project_id
     *
     * @param projectId the value for monitor_project_url.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_url.create_time
     *
     * @return the value of monitor_project_url.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_url.create_time
     *
     * @param createTime the value for monitor_project_url.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_project_url.update_time
     *
     * @return the value of monitor_project_url.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_project_url.update_time
     *
     * @param updateTime the value for monitor_project_url.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}