package com.ych.core.mapper;

import com.ych.core.model.AlarmRecord;
import com.ych.core.model.AlarmRecordExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AlarmRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    long countByExample(AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int deleteByExample(AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int insert(AlarmRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int insertSelective(AlarmRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    List<AlarmRecord> selectByExampleWithRowbounds(AlarmRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    List<AlarmRecord> selectByExample(AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    AlarmRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AlarmRecord record, @Param("example") AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AlarmRecord record, @Param("example") AlarmRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlarmRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlarmRecord record);
}