package com.ych.core.mapper;

import com.ych.core.model.AlarmSet;
import com.ych.core.model.AlarmSetExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AlarmSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    long countByExample(AlarmSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int deleteByExample(AlarmSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int insert(AlarmSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int insertSelective(AlarmSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    List<AlarmSet> selectByExampleWithRowbounds(AlarmSetExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    List<AlarmSet> selectByExample(AlarmSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    AlarmSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AlarmSet record, @Param("example") AlarmSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AlarmSet record, @Param("example") AlarmSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlarmSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlarmSet record);
}