package com.ych.core.mapper;

import com.ych.core.model.MonitorDetail;
import com.ych.core.model.MonitorDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MonitorDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    long countByExample(MonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int deleteByExample(MonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int insert(MonitorDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int insertSelective(MonitorDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    List<MonitorDetail> selectByExampleWithRowbounds(MonitorDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    List<MonitorDetail> selectByExample(MonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    MonitorDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MonitorDetail record, @Param("example") MonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MonitorDetail record, @Param("example") MonitorDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MonitorDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonitorDetail record);
}