package com.ych.core.mapper;

import com.ych.core.model.MonitorProjectUser;
import com.ych.core.model.MonitorProjectUserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MonitorProjectUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    long countByExample(MonitorProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int deleteByExample(MonitorProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int insert(MonitorProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int insertSelective(MonitorProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    List<MonitorProjectUser> selectByExampleWithRowbounds(MonitorProjectUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    List<MonitorProjectUser> selectByExample(MonitorProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    MonitorProjectUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MonitorProjectUser record, @Param("example") MonitorProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MonitorProjectUser record, @Param("example") MonitorProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MonitorProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonitorProjectUser record);
}