package com.ych.core.mapper;

import com.ych.core.model.MonitorSummary;
import com.ych.core.model.MonitorSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MonitorSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    long countByExample(MonitorSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int deleteByExample(MonitorSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int insert(MonitorSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int insertSelective(MonitorSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    List<MonitorSummary> selectByExampleWithRowbounds(MonitorSummaryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    List<MonitorSummary> selectByExample(MonitorSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    MonitorSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MonitorSummary record, @Param("example") MonitorSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MonitorSummary record, @Param("example") MonitorSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MonitorSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonitorSummary record);
}