package com.ych.core.mapper;

import com.ych.core.model.MonitorItem;
import com.ych.core.model.MonitorItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MonitorItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    long countByExample(MonitorItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int deleteByExample(MonitorItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int insert(MonitorItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int insertSelective(MonitorItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    List<MonitorItem> selectByExampleWithRowbounds(MonitorItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    List<MonitorItem> selectByExample(MonitorItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    MonitorItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MonitorItem record, @Param("example") MonitorItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MonitorItem record, @Param("example") MonitorItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MonitorItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonitorItem record);
}