package com.ych.core.mapper;

import com.ych.core.model.MonitorProject;
import com.ych.core.model.MonitorProjectExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MonitorProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    long countByExample(MonitorProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int deleteByExample(MonitorProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int insert(MonitorProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int insertSelective(MonitorProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    List<MonitorProject> selectByExampleWithRowbounds(MonitorProjectExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    List<MonitorProject> selectByExample(MonitorProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    MonitorProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MonitorProject record, @Param("example") MonitorProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MonitorProject record, @Param("example") MonitorProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MonitorProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonitorProject record);
}