package com.ych.core.mapper;

import com.ych.core.model.MonitorGroupItem;
import com.ych.core.model.MonitorGroupItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MonitorGroupItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    long countByExample(MonitorGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int deleteByExample(MonitorGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int insert(MonitorGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int insertSelective(MonitorGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    List<MonitorGroupItem> selectByExampleWithRowbounds(MonitorGroupItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    List<MonitorGroupItem> selectByExample(MonitorGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    MonitorGroupItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MonitorGroupItem record, @Param("example") MonitorGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MonitorGroupItem record, @Param("example") MonitorGroupItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MonitorGroupItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_group_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonitorGroupItem record);
}